version: '3'

volumes:
  database: {}

services:
  database:
    build: ./docker/postgres
    ports:
      - '5432:5432'
    volumes:
      - '.:/var/www:cached'
      - 'database:/var/lib/postgresql/data'

  node:
    build: ./docker/node
    depends_on:
      - database
    volumes:
      - '.:/var/www:cached'
    ports:
      - 3000:3000
